version: "3.9"

services:
  warehouse-svc:
    image: aw2-ecommerce/warehouse-svc
    container_name: warehouse-svc
    build:
      dockerfile: ../Dockerfile # relative to the build context
      context: ../warehouse-service/build
    #    restart: always
    env_file:
      - configs/warehouse-svc.env.prod
    networks:
      - warehouse-net
      - communication-net
    depends_on:
      - warehouse-db
      - kafka

  warehouse-db:
    image: "mongo:5.0.2"
    container_name: warehouse-db
    #    restart: always
    env_file:
      - configs/warehouse-db.env.prod
    #    ports:
    #      - "27017:27017"
    #    volumes:
    #      - warehouse-db-data:/data/db
    networks:
      - warehouse-net
      - kafka-net
    logging:
      driver: none