server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 5000
    expected-client-renewal-interval-seconds: 5
    renewal-threshold-update-interval-ms: 5000

