export enum ErrorType {
    ROUTE_NOT_FOUND,
    INVALID_REQUEST,
    INVALID_FIELDS,
    INTERNAL_ERROR,
    ORDER_NOT_FOUND,
    UNAUTHORIZED,
    ORDER_CREATION_FAILED,
    ORDER_STATUS_CHANGE_FAILED,
    ORDER_DELETION_FAILED
}

export default ErrorType